apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: a-simple-template
  title: A simple template
  description: This simple template is used for learning purposes.
spec:
  owner: rhdeveloper-book-authors
  type: service
  

